spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres #pragma: allowlist secret
  flyway:
    connect-retries: 3
  cloud:
    aws:
      region:
        static: ca-central-1
      s3:
        endpoint: http://s3.localhost.localstack.cloud:4566
      sqs:
        endpoint: http://sqs.localhost.localstack.cloud:4566
app:
  s3:
    bucket: localstack-bucket
  sqs:
    queue-name: localstack-queue
