services:
  localstack:
    image: localstack/localstack:3.0.2
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "./.localstack/init:/etc/localstack/init"
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack/.volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - "./.postgres/.data:/var/lib/postgresql/data"
