name: build-and-deploy
run-name: ${{github.actor}} builds and deploys
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          architecture: x64
          cache: maven
          server-id: vicopol-academy
      - name: Build and deploy with Maven
        run: ./mvnw --batch-mode --activate-profiles attach-sources,attach-javadocs clean deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
